const fs = require('fs');
let content = fs.readFileSync('server/routes.ts', 'utf8');
const newCode = [
'',
'  // Accept booking (provider action)',
'  app.post("/api/bookings/:id/accept", async (req, res) => {',
'    if (!req.isAuthenticated()) return res.status(401).json({ message: "Unauthorized" });',
'    try {',
'      const bookingId = Number(req.params.id);',
'      const userId = (req.user as any).id;',
'      const booking = await storage.getBooking(bookingId);',
'      if (!booking) return res.status(404).json({ message: "Booking not found" });',
'      const service = await storage.getService(booking.serviceId);',
'      if (!service || service.providerId !== userId) return res.status(403).json({ message: "Not authorized" });',
'      if (booking.status !== "pending") return res.status(400).json({ message: "Only pending bookings can be accepted" });',
'      await storage.updateBookingStatus(bookingId, "accepted");',
'      await storage.createNotification({ userId: booking.customerId, type: "booking_accepted", title: "Booking Accepted!", body: service.title + " accepted. The provider is on their way!", metadata: JSON.stringify({ bookingId, serviceId: service.id }) });',
'      res.json({ success: true, message: "Booking accepted" });',
'    } catch (err) { console.error("Accept booking error:", err); res.status(500).json({ message: "Failed to accept booking" }); }',
'  });',
'',
'  // Pause booking (provider action)',
'  app.post("/api/bookings/:id/pause", async (req, res) => {',
'    if (!req.isAuthenticated()) return res.status(401).json({ message: "Unauthorized" });',
'    try {',
'      const bookingId = Number(req.params.id);',
'      const userId = (req.user as any).id;',
'      const { reason } = req.body;',
'      const booking = await storage.getBooking(bookingId);',
'      if (!booking) return res.status(404).json({ message: "Booking not found" });',
'      const service = await storage.getService(booking.serviceId);',
'      if (!service || service.providerId !== userId) return res.status(403).json({ message: "Not authorized" });',
'      if (booking.status !== "accepted") return res.status(400).json({ message: "Only accepted bookings can be paused" });',
'      await storage.updateBookingStatus(bookingId, "paused");',
'      if (reason) await storage.updateBookingPausedReason(bookingId, reason);',
'      await storage.createNotification({ userId: booking.customerId, type: "booking_paused", title: "Job Paused", body: "Your job has been paused" + (reason ? ": " + reason : ""), metadata: JSON.stringify({ bookingId, serviceId: service.id }) });',
'      res.json({ success: true, message: "Booking paused" });',
'    } catch (err) { console.error("Pause booking error:", err); res.status(500).json({ message: "Failed to pause booking" }); }',
'  });',
'',
'  // Update provider location',
'  app.put("/api/users/location", async (req, res) => {',
'    if (!req.isAuthenticated()) return res.status(401).json({ message: "Unauthorized" });',
'    try {',
'      const userId = (req.user as any).id;',
'      const { lat, lng } = req.body;',
'      if (!lat || !lng) return res.status(400).json({ message: "lat and lng required" });',
'      await storage.updateUser(userId, { lat, lng });',
'      res.json({ success: true });',
'    } catch (err) { res.status(500).json({ message: "Failed to update location" }); }',
'  });',
'',
'  // Get provider location for active booking',
'  app.get("/api/bookings/:id/provider-location", async (req, res) => {',
'    if (!req.isAuthenticated()) return res.status(401).json({ message: "Unauthorized" });',
'    try {',
'      const bookingId = Number(req.params.id);',
'      const userId = (req.user as any).id;',
'      const booking = await storage.getBooking(bookingId);',
'      if (!booking) return res.status(404).json({ message: "Booking not found" });',
'      if (booking.customerId !== userId) return res.status(403).json({ message: "Not authorized" });',
'      if (booking.status !== "accepted") return res.status(400).json({ message: "Booking is not active" });',
'      const service = await storage.getService(booking.serviceId);',
'      if (!service) return res.status(404).json({ message: "Service not found" });',
'      const provider = await storage.getUser(service.providerId);',
'      if (!provider) return res.status(404).json({ message: "Provider not found" });',
'      res.json({ lat: provider.lat, lng: provider.lng });',
'    } catch (err) { res.status(500).json({ message: "Failed to get provider location" }); }',
'  });',
'',
].join("\n");
content = content.replace('  return httpServer;', newCode + '  return httpServer;');
fs.writeFileSync('server/routes.ts', content);
console.log('Endpoints agregados');
